/**
 * SEO + structured data helpers.
 *
 * Rule of thumb: only describe what is TRUE and VISIBLE on the page. No invented phone numbers, addresses,
 * hours, ratings or reviews. Business contact facts come from the `business` site settings (Admin → Site →
 * Business profile; pass them in — this module stays free of server-only imports) and the store record
 * (src/lib/store.ts). These OPTIONAL environment variables are fallbacks, emitted only when set:
 *
 *   APP_URL             Public base URL, e.g. https://www.example.com. Optional: without it the URL is worked out
 *                       automatically (hosting platform variables, then the request's own host, then the local
 *                       dev server's port). A localhost APP_URL is ignored in favour of the real address.
 *   STORE_NAME          Brand name used in metadata (fallback "PalletPort"; the DB store name is used in JSON-LD)
 *   STORE_PHONE         Customer-service phone, E.164 or display format, e.g. +1-614-555-0100
 *   STORE_EMAIL         Customer-service email
 *   STORE_STREET        Warehouse street address (only if buyers can visit / pick up there)
 *   STORE_POSTAL        Warehouse postal code
 *   STORE_COUNTRY       ISO country code for the address, e.g. US
 *   STORE_HOURS         Warehouse/pickup hours in schema.org format, e.g. "Mo-Fr 08:00-18:00" or "Mo-Fr 08:00-18:00; Sa 09:00-12:00"
 *   STORE_SAME_AS       Comma-separated official profile URLs (Google Business Profile, LinkedIn, Facebook, ...)
 *   ALLOW_AI_CRAWLERS   "false" disallows AI crawlers in robots.txt (default: allowed) — see src/app/robots.ts
 */
import type { Metadata } from "next";
import { CONDITIONS, LOT_SIZES } from "@/lib/format";
import { parseImages } from "@/lib/lotImages";
import { resolveImageRef } from "@/lib/imageRef";
import { photoSrc } from "@/content/photos";
import { DEFAULTS, rebrandText, type BusinessSettings, type SeoSettings } from "@/lib/settings-schema";

export { JsonLd } from "@/components/JsonLd";

export const SITE_NAME = process.env.STORE_NAME || "PalletPort";
export const SITE_TAGLINE = "Manifested liquidation pallets, truckloads and case packs direct from our warehouse";
export const DEFAULT_OG_IMAGE = "/opengraph-image";
/** Stable raster logo (512×512 PNG), generated by src/app/logo.png/route.tsx. */
export const LOGO_PATH = "/logo.png";

type Json = Record<string, unknown>;

// ---------- URLs ----------

const cleanUrl = (u: string) => u.trim().replace(/\/+$/, "");
const withProtocol = (host: string) => (/^https?:\/\//i.test(host) ? host : `https://${host}`);

/** True for http(s)://localhost, 127.0.0.1 or [::1], any port. */
export function isLocalUrl(u: string) {
  return /^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(:\d+)?(\/|$)/i.test(u);
}

/**
 * The public URL from configuration, or null: APP_URL (NEXT_PUBLIC_APP_URL also accepted), then the hosting
 * platform's own variable (Vercel, Netlify, Render, Railway, Fly). A localhost APP_URL doesn't count, so an old
 * "http://localhost:3000" in .env never overrides the port or domain the site is really served on.
 */
export function configuredSiteUrl(): string | null {
  const explicit = (process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL || "").trim();
  if (explicit && !isLocalUrl(explicit)) return cleanUrl(withProtocol(explicit));
  const env = process.env;
  const platform =
    env.VERCEL_PROJECT_PRODUCTION_URL ||
    (env.NETLIFY === "true" ? env.URL : "") ||
    env.RENDER_EXTERNAL_URL ||
    env.RAILWAY_PUBLIC_DOMAIN ||
    (env.FLY_APP_NAME ? `${env.FLY_APP_NAME}.fly.dev` : "") ||
    env.VERCEL_URL ||
    "";
  return platform ? cleanUrl(withProtocol(platform)) : null;
}

/**
 * Base URL of the site, without a trailing slash. Synchronous, for JSON-LD and helpers that can't await:
 * configured URL → the running Next.js server's own origin (right port in dev and `next start`) → localhost.
 * Server code that has a request should prefer `requestSiteUrl()` (src/lib/site-url.ts), which also knows the
 * host the visitor actually used.
 */
export function siteUrl() {
  return (
    configuredSiteUrl() ??
    cleanUrl(process.env.__NEXT_PRIVATE_ORIGIN || `http://localhost:${process.env.PORT || 3000}`)
  );
}

export function absoluteUrl(path = "/") {
  if (/^https?:\/\//i.test(path)) return path;
  return `${siteUrl()}${path.startsWith("/") ? "" : "/"}${path}`;
}

const ORG_ID = () => `${siteUrl()}/#organization`;
const WEBSITE_ID = () => `${siteUrl()}/#website`;

function env(name: string) {
  const v = process.env[name]?.trim();
  return v ? v : undefined;
}

// ---------- Metadata ----------

/** Trim to ≤ max chars at a word boundary (adds an ellipsis when cut). */
export function trimDescription(text: string | null | undefined, max = 155) {
  const clean = (text ?? "").replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const at = cut.lastIndexOf(" ");
  return `${(at > 60 ? cut.slice(0, at) : cut).replace(/[\s,;:.\-–—]+$/, "")}…`;
}

/**
 * Per-page metadata. Keep `title` ≤ ~60 characters including the " · PalletPort" suffix the root template adds
 * (so aim for ≤ 47 characters here), and write the description for a buyer, not a search engine.
 */
export async function pageMetadata({
  title,
  description,
  path,
  image,
  imageAlt,
  type = "website",
  noIndex = false,
  absoluteTitle = false,
  publishedTime,
  modifiedTime,
  authors,
}: {
  title: string;
  description?: string;
  path: string;
  image?: string;
  imageAlt?: string;
  type?: "website" | "article";
  noIndex?: boolean;
  /** Use the title as-is, without the " · PalletPort" template. */
  absoluteTitle?: boolean;
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
}): Promise<Metadata> {
  // Brand name from Admin → Business profile; text written with the original name follows a rename.
  const { getBrand } = await import("@/lib/brand");
  const brand = await getBrand();
  title = rebrandText(title, brand);
  description = description ? rebrandText(description, brand) : description;
  if (imageAlt) imageAlt = rebrandText(imageAlt, brand);
  const desc = description ? trimDescription(description) : undefined;
  const fullTitle = absoluteTitle || title.includes(brand) ? title : `${title} · ${brand}`;
  const img = { url: image ?? DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: imageAlt ?? fullTitle };
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description: desc,
    alternates: { canonical: path },
    openGraph: {
      siteName: brand,
      locale: "en_US",
      url: path,
      title: fullTitle,
      description: desc,
      images: [img],
      ...(type === "article" ? { type: "article" as const, publishedTime, modifiedTime, authors } : { type: "website" as const }),
    },
    twitter: { card: "summary_large_image", title: fullTitle, description: desc, images: [img.url] },
    // Public-but-thin pages (e.g. search results): keep out of the index but let crawlers follow the lot links.
    ...(noIndex ? { robots: { index: false, follow: true, googleBot: { index: false, follow: true } } } : {}),
  };
}

/** Absolute-or-root URL for a social image ref (stock key, media URL or https URL); "" → the generated OG image. */
export function ogImageUrl(ref: string | null | undefined) {
  const img = resolveImageRef(ref);
  if (img.kind === "stock") return photoSrc(img.photo, 1200, 1200 / 630);
  if (img.kind === "url") return img.src;
  return DEFAULT_OG_IMAGE;
}

/**
 * Site-wide metadata defaults for the root layout, from the `seo` settings (Admin → Site → SEO).
 * While the title/template are untouched, a STORE_NAME env override still replaces "PalletPort" in them.
 */
export function siteMetadata(seo: SeoSettings, brand = SITE_NAME, base = siteUrl()): Metadata {
  const swap = (v: string, _d: string) => rebrandText(v, brand);
  const title = swap(seo.defaultTitle, DEFAULTS.seo.defaultTitle);
  const template = swap(seo.titleTemplate, DEFAULTS.seo.titleTemplate);
  const image = ogImageUrl(seo.ogImage);
  const custom = image !== DEFAULT_OG_IMAGE;
  const description = seo.defaultDescription || undefined;
  // Shorter share text for social cards (falls back to the meta description).
  const shareDescription = "Manifested liquidation pallets, truckloads and case packs at fixed prices, sold direct from our Columbus, Ohio warehouse.";
  const ogImage = custom ? { url: image, width: 1200, height: 630, alt: title } : { url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: `${brand}: wholesale liquidation pallets` };
  const google = (seo.googleVerification || process.env.GOOGLE_SITE_VERIFICATION || "").trim();
  return {
    metadataBase: new URL(base),
    applicationName: brand,
    title: { default: title, template },
    description,
    keywords: [
      "liquidation pallets",
      "wholesale liquidation",
      "liquidation pallets for sale",
      "customer returns pallets",
      "overstock pallets",
      "truckload liquidation",
      "case packs",
      "bin store inventory",
      "liquidation pallets Columbus Ohio",
    ],
    authors: [{ name: brand, url: base }],
    creator: brand,
    publisher: brand,
    category: "Wholesale Liquidation",
    referrer: "origin-when-cross-origin",
    manifest: "/manifest.webmanifest",
    alternates: { canonical: "/" },
    formatDetection: { telephone: false, email: false, address: false },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    openGraph: { type: "website", locale: "en_US", url: "/", siteName: brand, title, description: shareDescription, images: [ogImage] },
    twitter: { card: "summary_large_image", title, description: shareDescription, images: [ogImage.url] },
    ...(google ? { verification: { google } } : {}),
  };
}

const NO_INDEX = { index: false, follow: false, googleBot: { index: false, follow: false } };

/** Metadata for private / transactional pages: a title for the tab, and never indexed. */
export function privateMetadata(title?: string): Metadata {
  return { ...(title ? { title } : {}), robots: NO_INDEX };
}

// ---------- Lot indexing rules (shared by lot metadata and the sitemap) ----------

/** Sold-out lots stay indexed this many days after the sale, then drop out (noindex + out of the sitemap). */
export const SOLD_INDEX_DAYS = 30;

type SoldLotLike = {
  createdAt: Date;
  /** Latest order line for the lot, newest first. */
  orderItems?: { order: { createdAt: Date } }[];
};

/** When a SOLD_OUT lot sold: its latest order, else the listing date. */
export function lotSoldAt(lot: SoldLotLike): Date {
  return lot.orderItems?.[0]?.order.createdAt ?? lot.createdAt;
}

/** ACTIVE lots are indexable; SOLD_OUT only within SOLD_INDEX_DAYS of the sale; DRAFT never. */
export function lotIndexable(lot: SoldLotLike & { status: string }, now = Date.now()): boolean {
  if (lot.status === "ACTIVE") return true;
  if (lot.status !== "SOLD_OUT") return false;
  return now - lotSoldAt(lot).getTime() <= SOLD_INDEX_DAYS * 86400000;
}

/** Prisma select for the latest order line of a lot (feeds lotSoldAt). */
export const LATEST_ORDER_SELECT = {
  select: { order: { select: { createdAt: true } } },
  orderBy: { order: { createdAt: "desc" as const } },
  take: 1,
};

// ---------- JSON-LD ----------

type StoreLike = { name: string; location: string; bio: string; pickup?: boolean };

/** "Columbus, OH" -> { addressLocality: "Columbus", addressRegion: "OH" } */
function parseLocation(location: string) {
  const parts = location.split(",").map((s) => s.trim()).filter(Boolean);
  if (!parts.length) return {};
  if (parts.length === 1) return { addressLocality: parts[0] };
  return { addressLocality: parts.slice(0, -1).join(", "), addressRegion: parts[parts.length - 1] };
}

/** Business contact facts used in JSON-LD (the `business` settings, already merged with STORE_* env by getSettings()). */
export type OrgBusiness = Pick<BusinessSettings, "email" | "phone" | "addressStreet" | "addressCity" | "addressRegion" | "addressPostal" | "country" | "socialLinks"> & { googleMapsUrl?: string; hours?: string; photos?: string[] };

function postalAddress(store: StoreLike, b?: OrgBusiness): Json | undefined {
  const parsed = parseLocation(store.location);
  const loc = b?.addressCity ? { addressLocality: b.addressCity, addressRegion: b.addressRegion || undefined } : parsed;
  const street = b?.addressStreet || env("STORE_STREET");
  const postal = b?.addressPostal || env("STORE_POSTAL");
  const country = b ? b.country || env("STORE_COUNTRY") : env("STORE_COUNTRY");
  if (!loc.addressLocality && !street) return undefined;
  return { "@type": "PostalAddress", streetAddress: street, ...loc, postalCode: postal, addressCountry: country };
}

const DAY: Record<string, string> = { Mo: "Monday", Tu: "Tuesday", We: "Wednesday", Th: "Thursday", Fr: "Friday", Sa: "Saturday", Su: "Sunday" };
const DAY_KEYS = Object.keys(DAY);

/** Parses "Mo-Fr 08:00-18:00; Sa 09:00-12:00". Returns undefined if anything doesn't parse (we'd rather emit nothing). */
function parseHours(spec: string | undefined): Json[] | undefined {
  if (!spec) return undefined;
  const out: Json[] = [];
  for (const part of spec.split(/[;,]/).map((s) => s.trim()).filter(Boolean)) {
    const m = part.match(/^([A-Z][a-z])(?:-([A-Z][a-z]))?\s+(\d{2}:\d{2})-(\d{2}:\d{2})$/);
    if (!m || !DAY[m[1]] || (m[2] && !DAY[m[2]])) return undefined;
    const from = DAY_KEYS.indexOf(m[1]);
    const to = m[2] ? DAY_KEYS.indexOf(m[2]) : from;
    if (to < from) return undefined;
    out.push({ "@type": "OpeningHoursSpecification", dayOfWeek: DAY_KEYS.slice(from, to + 1).map((d) => `https://schema.org/${DAY[d]}`), opens: m[3], closes: m[4] });
  }
  return out.length ? out : undefined;
}

/** "Monday–Friday, 8am–6pm ET" → opening hours (the free-text hours from Business settings). Undefined if it doesn't parse. */
function parseFriendlyHours(text: string | undefined): Json[] | undefined {
  const m = text?.match(/^\s*(mon|tue|wed|thu|fri|sat|sun)[a-z]*\.?\s*(?:[–—-]|to)\s*(mon|tue|wed|thu|fri|sat|sun)[a-z]*\.?,?\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*(?:[–—-]|to)\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)/i);
  if (!m) return undefined;
  const key = (d: string) => d.slice(0, 2).replace(/^./, (c) => c.toUpperCase());
  const t = (h: string, min: string | undefined, ap: string) => `${String((Number(h) % 12) + (ap.toLowerCase() === "pm" ? 12 : 0)).padStart(2, "0")}:${min ?? "00"}`;
  return parseHours(`${key(m[1])}-${key(m[2])} ${t(m[3], m[4], m[5])}-${t(m[6], m[7], m[8])}`);
}

/** Organization (OnlineStore) JSON-LD. Pass the `business` settings to prefer them over the STORE_* env vars. */
export function organizationJsonLd(store: StoreLike, business?: OrgBusiness): Json {
  const phone = business?.phone || env("STORE_PHONE");
  const email = business?.email || env("STORE_EMAIL");
  const sameAs = [
    ...(business?.socialLinks.map((l) => l.href) ?? []),
    ...(business?.googleMapsUrl ? [business.googleMapsUrl] : []),
    ...(env("STORE_SAME_AS")?.split(",").map((s) => s.trim()) ?? []),
  ].filter((s, i, all) => /^https?:\/\//.test(s) && all.indexOf(s) === i);
  const address = postalAddress(store, business);
  const street = business?.addressStreet || env("STORE_STREET");
  const hours = parseHours(env("STORE_HOURS")) ?? parseFriendlyHours(business?.hours);
  // Real warehouse photos (Business settings → Warehouse photos) first, then the logo.
  const photos = (business?.photos ?? []).filter((p) => /^(https?:\/\/|\/)/.test(p)).map((p) => absoluteUrl(p));
  // With a published street address the store is also a physical place (LocalBusiness), so Google can tie the
  // site to the address, photos and hours of the warehouse.
  const physical = Boolean(street && address);
  return {
    "@context": "https://schema.org",
    "@type": physical ? ["OnlineStore", "WholesaleStore"] : "OnlineStore",
    "@id": ORG_ID(),
    name: store.name,
    url: `${siteUrl()}/`,
    logo: { "@type": "ImageObject", url: absoluteUrl(LOGO_PATH), width: 512, height: 512 },
    image: [...photos, absoluteUrl(LOGO_PATH)],
    description: store.bio,
    address,
    hasMap: physical && business?.googleMapsUrl ? business.googleMapsUrl : undefined,
    openingHoursSpecification: physical ? hours : undefined,
    // A pickup location is only described when the owner has published a real street address.
    location:
      store.pickup && street && address
        ? { "@type": "Place", name: `${store.name} warehouse`, address, photo: photos.length ? photos : undefined, openingHoursSpecification: hours }
        : undefined,
    contactPoint:
      phone || email
        ? { "@type": "ContactPoint", contactType: "customer service", telephone: phone, email, availableLanguage: "English", url: absoluteUrl("/contact") }
        : undefined,
    telephone: phone,
    email,
    sameAs: sameAs?.length ? sameAs : undefined,
  };
}

export function websiteJsonLd(name = SITE_NAME): Json {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": WEBSITE_ID(),
    name,
    url: `${siteUrl()}/`,
    inLanguage: "en-US",
    publisher: { "@id": ORG_ID() },
    potentialAction: {
      "@type": "SearchAction",
      target: { "@type": "EntryPoint", urlTemplate: `${siteUrl()}/search?q={search_term_string}` },
      "query-input": "required name=search_term_string",
    },
  };
}

export type Crumb = { name: string; path: string };

export function breadcrumbJsonLd(items: Crumb[]): Json {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((c, i) => ({ "@type": "ListItem", position: i + 1, name: c.name, item: absoluteUrl(c.path) })),
  };
}

const ITEM_CONDITION: Record<string, string> = {
  NEW: "https://schema.org/NewCondition",
  SHELF_PULL: "https://schema.org/NewCondition",
  CUSTOMER_RETURN: "https://schema.org/UsedCondition",
  MIXED: "https://schema.org/UsedCondition",
  SALVAGE: "https://schema.org/DamagedCondition",
};

const AVAILABILITY: Record<string, string> = {
  ACTIVE: "https://schema.org/InStock",
  SOLD_OUT: "https://schema.org/SoldOut",
};

type LotForSchema = {
  id: string;
  slug: string;
  title: string;
  description: string;
  externalSku?: string | null;
  sku: string;
  condition: string;
  priceCents: number;
  msrpCents: number;
  units: number;
  palletCount: number;
  lotSize: string;
  weightLbs?: number;
  brand?: string;
  status: string;
  available?: number;
  images?: string | null;
  category?: { name: string } | null;
  subcategory?: { name: string } | null;
};

const dollars = (cents: number) => (cents / 100).toFixed(2);

/** The "Lot #" shown on lot pages. */
export const lotNumber = (lot: { id: string }) => lot.id.slice(-6).toUpperCase();

export function productJsonLd(lot: LotForSchema, sellerName = SITE_NAME): Json {
  const url = absoluteUrl(`/lots/${lot.slug}`);
  // Only real uploaded photos describe the product. Stock photos are illustrative, so they're left out.
  const images = parseImages(lot.images).map((src) => absoluteUrl(src));
  const props: Json[] = [
      ...(lot.units > 0 ? [{ "@type": "PropertyValue", name: "Units", value: lot.units }] : []),
    { "@type": "PropertyValue", name: "Lot size", value: LOT_SIZES[lot.lotSize]?.label ?? lot.lotSize },
    ...(lot.lotSize === "CASE" ? [] : [{ "@type": "PropertyValue", name: "Pallets", value: lot.palletCount }]),
      ...(lot.msrpCents > 0 ? [{ "@type": "PropertyValue", name: "Estimated retail value", value: Number(dollars(lot.msrpCents)), unitText: "USD" }] : []),
    { "@type": "PropertyValue", name: "Condition grade", value: CONDITIONS[lot.condition]?.label ?? lot.condition },
  ];
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": `${url}#product`,
    name: lot.title,
    description: lot.description,
    sku: lot.sku,
    url,
    category: lot.subcategory && lot.category ? `${lot.category.name} > ${lot.subcategory.name}` : lot.category?.name,
    brand: lot.brand ? { "@type": "Brand", name: lot.brand } : undefined,
    itemCondition: ITEM_CONDITION[lot.condition],
    image: images.length ? images : undefined,
    weight: lot.weightLbs ? { "@type": "QuantitativeValue", value: lot.weightLbs, unitCode: "LBR" } : undefined,
    additionalProperty: props,
    offers: {
      "@type": "Offer",
      url,
      priceCurrency: "USD",
      price: dollars(lot.priceCents),
      availability: AVAILABILITY[lot.status] ?? "https://schema.org/InStock",
      itemCondition: ITEM_CONDITION[lot.condition],
      seller: { "@type": "Organization", "@id": ORG_ID(), name: sellerName },
      ...(lot.status === "ACTIVE" && lot.available ? { inventoryLevel: { "@type": "QuantitativeValue", value: lot.available } } : {}),
    },
  };
}

type PostLike = { slug: string; title: string; excerpt: string; date?: string; updated?: string; category?: string; tags?: string[] };

export function articleJsonLd(post: PostLike, opts: { authorName: string; image?: string; path?: string }): Json {
  const url = absoluteUrl(opts.path ?? `/blog/${post.slug}`);
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.excerpt,
    datePublished: post.date,
    dateModified: post.updated ?? post.date,
    // Bylines on this site are team names, so the author is an Organization rather than a Person.
    author: { "@type": "Organization", name: opts.authorName, url: `${siteUrl()}/about` },
    publisher: { "@id": ORG_ID() },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    url,
    image: opts.image ? [opts.image] : undefined,
    articleSection: post.category,
    keywords: post.tags?.length ? post.tags.join(", ") : undefined,
    inLanguage: "en-US",
  };
}

/** Only use where the questions AND answers are visible on the page. */
export function faqJsonLd(items: { q: string; a: string }[]): Json | null {
  const list = items.filter((i) => i.q.trim() && i.a.trim());
  if (!list.length) return null;
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: list.map((i) => ({ "@type": "Question", name: i.q, acceptedAnswer: { "@type": "Answer", text: i.a } })),
  };
}

export function itemListJsonLd(name: string, lots: { slug: string; title: string }[]): Json {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: lots.length,
    itemListElement: lots.map((l, i) => ({ "@type": "ListItem", position: i + 1, url: absoluteUrl(`/lots/${l.slug}`), name: l.title })),
  };
}

/** Plain-text of an Article body (used for FAQ answers, which must match the visible text). */
export function sectionsText(body: { p?: string[]; list?: string[] }[]) {
  return body.flatMap((s) => [...(s.p ?? []), ...(s.list ?? [])]).join(" ").replace(/\s+/g, " ").trim();
}

/** WebPage subtypes for About / Contact. */
export function webPageJsonLd(type: "AboutPage" | "ContactPage" | "CollectionPage" | "WebPage", name: string, path: string, description?: string): Json {
  return {
    "@context": "https://schema.org",
    "@type": type,
    name,
    url: absoluteUrl(path),
    description,
    isPartOf: { "@id": WEBSITE_ID() },
    about: { "@id": ORG_ID() },
  };
}
