import assert from 'node:assert/strict';
import { buildMerchantFeed } from '../src/lib/merchant-feed';
import { cleanProductPhotos } from '../src/lib/product-photos';
import overrides from '../src/content/product-photo-overrides.json';
type Product = Parameters<typeof buildMerchantFeed>[0][number];
const product: Product = {sku:'PP-ABCDEF123456',slug:'lot-one',title:'Lot & Goods',description:'Products <b>with tags</b> & assorted sizes',images:'/images/products/0123456789abcdef.webp',status:'ACTIVE',available:1,priceCents:12345,condition:'NEW',sourceCondition:'New with tags',externalSku:'GS-1',externalUrl:'https://goldstackliquidation.com/product/lot-one',brand:'Example',lotSize:'PALLET',weightLbs:0,category:{name:'Clothing'}};
const base = 'https://example.com';
const feed = buildMerchantFeed([product],base);
assert.equal(feed.listed,1);
assert.ok(feed.body.includes('<g:id>PP-ABCDEF123456</g:id>'));
assert.ok(feed.body.includes('<g:price>123.45 USD</g:price>'));
assert.ok(feed.body.includes('https://example.com/images/products/0123456789abcdef.webp'));
assert.ok(feed.body.includes('Lot &amp; Goods'));
assert.ok(feed.body.includes('<g:structured_description>'));
assert.ok(!feed.body.includes('Full manifest')&&!feed.body.includes('g:is_bundle'));
for (const bad of [{images:''},{images:'/images/catalog/stock.webp'},{images:'https://images.unsplash.com/photo-1'},{available:0},{status:'DRAFT'},{priceCents:0}]) assert.equal(buildMerchantFeed([{...product,...bad}],base).listed,0);
assert.equal(buildMerchantFeed([{...product,externalSku:'JAX-1',externalUrl:'https://jaxwholesaleliquidation.com/products/lot-one',images:'https://jaxwholesaleliquidation.com/media/product-images/123'}],base).listed,1);
assert.equal(buildMerchantFeed([{...product,externalUrl:'https://other.example/product',images:'https://jaxwholesaleliquidation.com/media/product-images/123'}],base).listed,0);
const gallery = Array.from({length:15},(_,i)=>`/images/products/${i.toString(16).padStart(16,'0')}.webp`);
const many = buildMerchantFeed([{...product,images:gallery.join('\n')+'\n'+gallery[0]}],base).body;
assert.equal((many.match(/<g:additional_image_link>/g)??[]).length,10);
const removed = Object.entries(overrides).filter(([,value])=>value===null).map(([url])=>url);
assert(removed.length>0);
assert.deepEqual(cleanProductPhotos(removed),[]);
const edited = Object.entries(overrides).find(([url,value])=>url.startsWith('http')&&value?.endsWith('.png'))!;
assert.equal(buildMerchantFeed([{...product,images:removed.join('\n')}],base).listed,0);
assert(buildMerchantFeed([{...product,images:edited[0]}],base).body.includes(base+edited[1]));
assert.deepEqual(cleanProductPhotos([edited[0],edited[0],...removed]),[edited[1]]);
console.log('Merchant feed gallery, SKU, pricing, escaping, and exclusion checks passed.');
